name: EnderShare
author: i_Jedi
website: https://www.twitter.com/iJediPVP
main: me.i_Jedi.EnderShare.Main
version: 1.0.2
commands:
   ESHARE:
      description: Display EnderShare commands.
      usage: /eshare

permissions:
   enderShare.*:
      description: Give access to all of the EnderShare commands.
      children:
         enderShare.eShare: true
         enderShare.eShare.create: true
         enderShare.eShare.accept: true
         enderShare.eShare.disband: true
   enderShare.eShare:
      description: Give access to the /eshare command.
   enderShare.eShare.create:
      description: Give access to the /eshare create <player> command.
   enderShare.eShare.accept:
      description: Give access to the /eshare accept <player> command.
   enderShare.eShare.disband:
      description: Give access to the /eshare disband command.